### ISSUE TITLE
Not an Issue more of a question

### ISSUE THREAD

**Issue by wabj** [Flodu31/HomeAssistant-PeugeotIntegration#15]
Hi,

Thanks for this integration :)

Is there anyway to change km to mi at all?

**Comment by dreimer1986** [comment]
How about some calculation?
```
      e208_mileage:
        friendly_name: "Kilometerstand"
        unit_of_measurement: "km"
        value_template: "{{ ((state_attr('sensor.peugeot_e208', 'timed_odometer')['mileage']) / 1.609) | round(2)}}"
```
