### ISSUE TITLE
help

### ISSUE THREAD

**Issue by wifi75** [Flodu31/HomeAssistant-PeugeotIntegration#38]
Hello, What do you want to say with the by **replacing the URL with your own::**

I need to change this like this?

 resource: http://192.168.52:5000/get_vehicleinfo/12345678956454?from_cache=1

it is correct?

after check configuration I have this error:

![image](https://user-images.githubusercontent.com/31816231/230760966-37226f9a-1345-49b5-abdc-14bccecacf69.png)

**Comment by Flodu31** [comment]
Hello,yes it is correct.FlorentLe 9 avr. 2023 à 09:44, wifi75 ***@***.***> a écrit :﻿
Hello, What do you want to say with the by replacing the URL with your own::
I need to change this like this?
resource: http://192.168.52:5000/get_vehicleinfo/12345678956454?from_cache=1
it is correct?

**Comment by wifi75** [comment]
and for error?

**Comment by wifi75** [comment]
hello after set charging_threshold 
I have this error why?

![image](https://user-images.githubusercontent.com/31816231/230844730-44fe356a-550e-4680-9fb1-6a3231e044fd.png)

**Comment by Flodu31** [comment]
Can you send screenshot in english please?
I can't help here.

**Comment by wifi75** [comment]
> Can you send screenshot in english please? I can't help here.

![image](https://user-images.githubusercontent.com/31816231/231082114-6051ca40-64bf-4415-951e-c0cdcf557532.png)

**Comment by wifi75** [comment]
maybe command correct is 
rest_command: ec4_change_charge_threshold and not
rest_command: ec4_change_charging_threshold like you readme 

see below:

![image](https://user-images.githubusercontent.com/31816231/231083066-0006a411-ed29-453f-b8e9-efab832250f8.png)

**Comment by Flodu31** [comment]
I didn't created this for ec4
@stevoh6 can you help with this?

Thanks.
Florent

**Comment by Flodu31** [comment]
Just checked and I have this on my side:

```
- id: '1674076078097'
  alias: e2008 - Apply Charging Threshold
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_button.e2008_apply_charge_threshold_button
  condition: []
  action:
  - service: rest_command.e2008_change_charge_threshold
    data: {}
  mode: single
```
