### ISSUE TITLE
Plugin issue with HA version 2023.06 

### ISSUE THREAD

**Issue by drumstick77** [Flodu31/HomeAssistant-PeugeotIntegration#41]
Hi all,

as you probably know that the latest HA has introduced diff way of introducing sensors and command line.
I'm just wondering if I can please get some guide on this?
I've tried following the syntax for command line within configuration.yaml to no avail.
and if I understand this right, we can no longer use sensors.yaml? so all of them needs to go back to configuration.yaml?

**Comment by dreimer1986** [comment]
Only one sensor has to be changed here. At least in my very modded version:

```
command_line:
  - switch:
      name: e208_clim
      unique_id: e208_clim
      command_on: curl -s "http://192.168.181.42:5000/preconditioning/VIM/1"
      command_off: curl -s "http://192.168.181.42:5000/preconditioning/VIM/0"
```
