### ISSUE TITLE
Add SOH Sensor

### ISSUE THREAD

**Issue by zazazouthecat** [Flodu31/HomeAssistant-PeugeotIntegration#74]
Hi, 
My contribution - SOH Sensor
```
# peugeot_e2008 soh_control
- platform: rest
  name: peugeot_e2008_soh_control
  resource: http://IPofTheSoftware:5000/battery/soh/YourVIN
  scan_interval: 60
  timeout: 300
  value_template: 'OK'
  json_attributes:
   - soh
- platform: template
  sensors:
    e2008_battery_soh:
      friendly_name: "Battery SOH"
	  unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.peugeot_e2008_battery_soh', 'soh') }}"
      icon_template: mdi:battery-heart-variant
```
