### ISSUE TITLE
use home assistant package and other goodies to ease the installation

### ISSUE THREAD

**Issue by sanzoghenzo** [Flodu31/HomeAssistant-PeugeotIntegration#83]
Hi there!
Thanks a lot for this documentation, it has been helpful to start tinkering with my opel corsa-e and home assistant!

Trying to keep things as tidy as possible in my home assistant config, I discovered one can use [packages](https://www.home-assistant.io/docs/configuration/packages/) to group various entities, automation and so on in a single file/folder.

I also combined the rest and template sensors using the restful integration, and added input_texts/secrets to set the URL and VIN.

I'm still testing this, but that's what I got so far. If you want, you can use it to update the documentation!

This is my `opel_corsa.yaml` file:

```yaml
# Opel Corsa integration using psa-car-controller

input_text:
  psacc_url:
    name: "PSA Car Controller URL"
    initial: !secret psacc_url
  psacc_vin:
    name: "PSA Car Controller VIN"
    initial: !secret psacc_vin

rest:
  - resource_template: "{{ states('input_text.psacc_url') }}/get_vehicleinfo/{{ states('input_text.psacc_vin') }}?from_cache=1"
    scan_interval: 60
    timeout: 30
    sensor:
      - name: "Battery Voltage"
        unique_id: corsa_battery_voltage
        json_attributes:
          - battery
        unit_of_measurement: "V"
        value_template: '{{ value_json["battery"]["voltage"] * 4 }}'
      - name: "Battery"
        unique_id: corsa_battery_level
        json_attributes:
          - energy
        unit_of_measurement: "%"
        value_template: '{{ value_json["energy"][0]["level"] }}'
      - name: "Autonomy"
        unique_id: corsa_autonomy
        json_attributes:
          - energy
        unit_of_measurement: "km"
        value_template: '{{ value_json["energy"][0]["autonomy"] }}'
      - name: "Charging Status"
        unique_id: corsa_charging_status
        json_attributes:
          - energy
        value_template: '{{ value_json["energy"][0]["charging"]["status"] }}'
      - name: "Mileage"
        unique_id: corsa_mileage
        json_attributes:
          - timed_odometer
        unit_of_measurement: "km"
        value_template: '{{ value_json["timed_odometer"]["mileage"] }}'

  - resource_template: "{{ states('input_text.psacc_url') }}/charge_control?vin={{ states('input_text.psacc_vin') }}&?always_check=true"
    scan_interval: 60
    timeout: 30
    sensor:
      - name: "Next Stop Time"
        unique_id: corsa_next_stop_hour
        json_attributes:
          - _next_stop_hour
        value_template: '{{ value_json["_next_stop_hour"]}}'
      - name: "Threshold"
        unique_id: corsa_charge_threshold
        unit_of_measurement: "%"
        json_attributes:
          - percentage_threshold
        value_template: '{{ value_json["percentage_threshold"] }}'

# this one should be changed to use shell command + template switch to allow templating
command_line:
  - switch:
      name: corsa_clima
      unique_id: corsa_clima
      command_on: curl -s "http://YOURADDRESS:PORT/preconditioning/YOURVIN/1"
      command_off: curl -s "http://YOURADDRESS:PORT/preconditioning/YOURVIN/0"

rest_command:
  # WakeUp command
  corsa_wakeup:
    url: "{{ states('input_text.psacc_url') }}/wakeup/{{ states('input_text.psacc_vin') }}"

  # custom charging threshold
  corsa_change_charge_threshold:
    url: "{{ states('input_text.psacc_url') }}/charge_control?vin={{ states('input_text.psacc_vin') }}&percentage={{ states('input_number.corsa_charge_threshold_slider') | int }}"
    method: GET

  corsa_change_charge_hour:
    url: "{{ states('input_text.psacc_url') }}/charge_control?vin={{ states('input_text.psacc_vin') }}&hour={{ states('input_number.corsa_charge_delay_hour') }}&minute=0"

input_number:
  corsa_charge_threshold_slider:
    name: Charging threshold
    initial: 80
    min: 50
    max: 100
    step: 1
    unit_of_measurement: "%"

  corsa_charge_delay_hour:
    name: Charging delay
    initial: 0
    min: 0
    max: 24
    step: 1
    unit_of_measurement: "h"

input_button:
  corsa_apply_charge_threshold_button:
    name: Set charging threshold
    icon: mdi:battery-charging

# state initalization
homeassistant:
  customize:
    switch.corsa_clima:
      assumed_state: false

automation:
  - alias: WakeUp corsa
    trigger:
      - platform: time
        at: '6:00:00'
    condition: []
    action:
      - service: rest_command.corsa_wakeup
    mode: single
  - alias: Change charging threshold corsa
    trigger:
      - platform: state
        entity_id:
          - input_button.corsa_apply_charge_threshold_button
    condition: []
    action:
      - service: rest_command.corsa_change_charge_threshold
        data: {}
    mode: single
```

in `configuration.yaml`, you just need to:

```yaml
homeassistant:
  packages:
    opel_corsa: !include opel_corsa.yaml
```

and in `secrets.yaml` - note that this is not needed if you set the initial value of the `input_text`s to a string

```
psacc_url: http://YOURADDRESS:PORT
psacc_vin: YOURVIN
```

**Comment by gpayant** [comment]
Hello, fantastic, it works very well.
Thank you very much

**Comment by FynnleyNeko** [comment]
Odd for me this only loads the lower resource_template block.
If i switch them around the one that shows changes

**Comment by LeoAlioth** [comment]
in configuration.yaml, it should be
```
homeassistant:
  packages:
    opel_corsa: !include opel_corsa.yaml
```

**Comment by sanzoghenzo** [comment]
> in configuration.yaml, it should be
> 
> ```
> homeassistant:
>   packages:
>     opel_corsa: !include opel_corsa.yaml
> ```

Good catch, I've updated my instructions

**Comment by kveldscholten** [comment]
Hi, thx for your code!
but the miles and other information are not show and by change the Charging threshold, the change will not transferred.
I checked with direct link /charge_control?vin=xxxxx

![Image](https://github.com/user-attachments/assets/ecf8f78d-70ca-4656-bee9-640eada2efe8)

The following error appears in the Home Assistant log:
_REST result could not be parsed as JSON_

If I call the URL directly with /charge_control?vin=XXXXX I get a JSON string back

I use the newest HA Core version 2025.1.3
PSA Car Controller version v3.5.3

**Comment by bell07** [comment]
The real preconditioning is avaliable by 

```
      - name: "Preconditionning Status"
        unique_id: corsa_preconditionning_status
        json_attributes:
          - preconditionning
        value_template: '{{ value_json["preconditionning"]["air_conditioning"]["status"] }}'
```
Maybe it is possible to combine the value with the preconditioning switch? (I am new with home-assistant)


Other useful sensor:
```
      - name: "Corsa Ignition Status"
        unique_id: corsa_ignition
        json_attributes:
          - ignition
        value_template: '{{ value_json["ignition"]["type"] }}'
```

The Automation part I removed for me, because does not match my needs and same can be created using home-assistant UI. Maybe an automation template (if possible) would be beter?

**Comment by bell07** [comment]
Got the Precondition switch working. Only issue remains with status update delay. If I enable the switch, the switch goes back to disabled till the server confirm the precondition is enabled.

```
rest:
...
    sensor:
...
      - name: "Corsa Preconditionning Status"
        unique_id: corsa_preconditionning_status
        value_template: '{{ value_json["preconditionning"]["air_conditioning"]["status"] }}'

...
rest_command:
...
  corsa_preconditionning_enable:
    url: "{{ states('input_text.psacc_url') }}/preconditioning/{{ states('input_text.psacc_vin') }}/1"

  corsa_preconditionning_disable:
    url: "{{ states('input_text.psacc_url') }}/preconditioning/{{ states('input_text.psacc_vin') }}/0"
...

switch:
  - platform: template
    switches:
      corsa_preconditionning:
        unique_id: corsa_preconditionning
        value_template: "{{ is_state('sensor.corsa_preconditionning_status', 'Enabled') }}"
        turn_on:
          action: rest_command.corsa_preconditionning_enable
          target:
            entity_id: sensor.corsa_preconditionning_status

        turn_off:
          action: rest_command.corsa_preconditionning_disable
          target:
            entity_id: sensor.corsa_preconditionning_status
```


Removed parts:

```
# this one should be changed to use shell command + template switch to allow templating
command_line:
  - switch:
      name: corsa_clima
      unique_id: corsa_clima
      command_on: curl -s "http://YOURADDRESS:PORT/preconditioning/YOURVIN/1"
      command_off: curl -s "http://YOURADDRESS:PORT/preconditioning/YOURVIN/0"
```

```
# state initalization
homeassistant:
  customize:
    switch.corsa_clima:
      assumed_state: false
```
