### ISSUE TITLE
lastPosition sensors - status "unavailable"

### ISSUE THREAD

**Issue by Cassiopea1** [Flodu31/HomeAssistant-PeugeotIntegration#9]
I've added in sensor.yaml

    json_attributes:
      - ...
      - kinetic
      - lastPosition

and

      e208_moving:
        friendly_name: "Moving"
        value_template: '{{ states.sensor.peugeot_e208.attributes["kinetic"]["moving"] }}'

      e208_longitude:
        friendly_name: "Position longitude"
        unit_of_measurement: "°"
        value_template: '{{ states.sensor.peugeot_e208.attributes["lastPosition"]["geometry"]["coordinates"][0] }}'

      e208_latitude:
        friendly_name: "Position latitude"
        unit_of_measurement: "°"
        value_template: '{{ states.sensor.peugeot_e208.attributes["lastPosition"]["geometry"]["coordinates"][1] }}'

The "Moving" sensor is OK:

![image](https://user-images.githubusercontent.com/84228832/132853038-a99b0155-e463-4689-ab03-9e63736e3b5c.png)

but the "Position longitude" and "Position latitude" have the status unavailable.

![image](https://user-images.githubusercontent.com/84228832/132853366-13a0da25-544c-4ad3-aa07-0f92cd49e485.png)

My own python script reports:

    "kinetic": {
        "createdAt": "2021-09-10T10:29:40Z",
        "moving": false
    },
    "lastPosition": {
        "geometry": {
            "coordinates": [
                16.vwxyz,
                47.zyxwv,
                282
            ],
            "type": "Point"
        },
        "properties": {
            "signalQuality": 9,
            "type": "Aquire",
            "updatedAt": "2021-09-10T10:29:40Z"
        },
        "type": "Feature"
    },

so it should be OK.
Ideas?

Thanks

**Comment by Flodu31** [comment]
Hello,

Apparently, it is ok.
I can't test on my side, because I have null values for kinetic and lastPosition 🈂️ 

Sorry.
Florent

**Comment by dreimer1986** [comment]
Sadly like most of us...
Before it hit me, too. I used

configuration.yaml:
```
value_template: "{{ state_attr('sensor.peugeot_e208', 'last_position')['geometry']['coordinates'] }}"
```

automations.yaml:
```
- id: car_track
  alias: Tracker Car
  trigger:
  - entity_id: sensor.e208_mapdata
    platform: state
  - event: start
    platform: homeassistant
  action:
  - data:
      dev_id: car
      battery: '{{states.sensor.e208_battery_level.state}}'
      gps_accuracy: '15'
      gps:
      - '{{ (state_attr("sensor.peugeot_e208", "last_position")["geometry"]["coordinates"][1]) }}'
      - '{{ (state_attr("sensor.peugeot_e208", "last_position")["geometry"]["coordinates"][0]) }}'
    service: device_tracker.see
  mode: single
```

known_devices.yaml
```
car:
  name: Mein 208e
  icon: mdi:car-hatchback
  picture: /local/peugeot.png
  track: true
```

P.S. It worked for me in the past, I can't verify it due to:
```
"last_position": {"type": "Feature", "geometry": {"coordinates": [null, null, null], "type": "Point"}, "properties": {"heading": null, "signal_quality": null, "type": null, "updated_at": null}},
```

Try it and if it works, be happy with it as long as it lasts...
