### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by AymericLeFeyer** [Flodu31/HomeAssistant-PeugeotIntegration#93]
Hello !
I have successfully installed PSA Car Controller via HA Addons, and it's working
When I try to add sensors, I have a 401 Unauthorized error, because of cookie "ingress_session" (I think)
What can I do to fix my issue ?

### PSA Car Controller
![Image](https://github.com/user-attachments/assets/6a0d93e6-7b1b-4fe9-ae58-e28630de0995)

### CURL Without cookie
![Image](https://github.com/user-attachments/assets/652f48d4-23c7-4ad8-aabe-b21aa77a2a07)

### CURL With cookie
![Image](https://github.com/user-attachments/assets/54c8663f-64a2-438a-b6d0-233494d16476)

### Home Assistant
For debugging, I set `value_template: "{{ value | tojson }}"` 
```
- platform: rest
  name: peugeot_3008
  resource: ip/get_vehicleinfo/vin?from_cache=1
  scan_interval: 60
  timeout: 30
  value_template: "{{ value | tojson }}"
  json_attributes:
    - energy
    - timed_odometer
    - battery
``` 

And I have that 
![Image](https://github.com/user-attachments/assets/3a8eb7c5-96c2-468b-8c16-909b16d8efb6)

Should I set the cookie by hand ? I think it will expires soon ...
